# Generated by Django 4.2.2 on 2023-07-11 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('o11y', '0001_initial'), ('o11y', '0002_alter_resource_attributes_hash'), ('o11y', '0003_scopemetrics'), ('o11y', '0004_metric_scalarmetric_numberdatapoint'), ('o11y', '0005_remove_protometric_scope_metrics_and_more')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attributes_hash', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=256)),
                ('value', models.CharField(max_length=256)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='o11y.resource')),
            ],
        ),
        migrations.CreateModel(
            name='ScopeMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=256)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='o11y.resource')),
            ],
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('unit', models.CharField(max_length=32)),
                ('scope_metrics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='o11y.scopemetrics')),
            ],
        ),
        migrations.CreateModel(
            name='ScalarMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(max_length=256)),
                ('aggregation_temporality', models.IntegerField()),
                ('is_monotonic', models.BooleanField()),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='o11y.metric')),
            ],
        ),
        migrations.CreateModel(
            name='NumberDataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('time', models.DateTimeField()),
                ('int_value', models.IntegerField(default=0)),
                ('scalar_metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='o11y.scalarmetric')),
            ],
        ),
    ]
