# Generated by Django 4.2.2 on 2023-07-27 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('o11y', '0001_squashed_0005_remove_protometric_scope_metrics_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScopeLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=256)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='o11y.resource')),
            ],
        ),
        migrations.CreateModel(
            name='LogRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('severity_number', models.IntegerField()),
                ('severity_text', models.CharField(max_length=256)),
                ('body', models.TextField()),
                ('trace_id', models.CharField(max_length=256)),
                ('span_id', models.CharField(max_length=256)),
                ('scope_logs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='o11y.scopelogs')),
            ],
        ),
    ]
