# Generated by Django 5.0.1 on 2024-01-08 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("o11y", "0006_scopelogs_logrecord"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScopeSpans",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scope", models.CharField(max_length=256)),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="o11y.resource"
                    ),
                ),
            ],
        ),
    ]
