# Generated by Django 5.0.1 on 2024-01-08 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("o11y", "0007_scopespans"),
    ]

    operations = [
        migrations.CreateModel(
            name="Span",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                (
                    "scope_spans",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="o11y.scopespans",
                    ),
                ),
            ],
        ),
    ]
