# Generated by Django 5.0.1 on 2024-01-08 22:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("o11y", "0008_span"),
    ]

    operations = [
        migrations.AddField(
            model_name="span",
            name="span_id",
            field=models.CharField(default="x", max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="span",
            name="trace_id",
            field=models.CharField(default="y", max_length=32),
            preserve_default=False,
        ),
    ]
