# Generated by Django 5.0.1 on 2024-01-08 23:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("o11y", "0009_span_span_id_span_trace_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="span",
            name="kind",
            field=models.CharField(default="z", max_length=64),
            preserve_default=False,
        ),
    ]
