# Generated by Django 5.0.1 on 2024-01-08 23:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("o11y", "0010_span_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="span",
            name="kind",
            field=models.IntegerField(
                choices=[
                    (1, "Server"),
                    (2, "Client"),
                    (3, "Producer"),
                    (4, "Consumer"),
                    (5, "Internal"),
                ]
            ),
        ),
    ]
