# Generated by Django 5.0.1 on 2024-01-09 20:10
import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("o11y", "0011_alter_span_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="span",
            name="end_time",
            field=models.DateTimeField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="span",
            name="start_time",
            field=models.DateTimeField(),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="span",
            name="kind",
            field=models.IntegerField(
                choices=[
                    (0, "Unspecified"),
                    (1, "Internal"),
                    (2, "Server"),
                    (3, "Client"),
                    (4, "Producer"),
                    (5, "Consumer"),
                ]
            ),
        ),
    ]
