# Generated by Django 5.0.1 on 2024-01-09 20:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("o11y", "0012_span_end_time_span_start_time_alter_span_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="span",
            name="parent_span_id",
            field=models.CharField(default="x", max_length=16),
            preserve_default=False,
        ),
    ]
