# Generated by Django 5.0.1 on 2024-01-09 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("o11y", "0013_span_parent_span_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="span",
            name="parent_span_id",
        ),
        migrations.AddField(
            model_name="span",
            name="parent_span",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child_spans",
                to="o11y.span",
            ),
        ),
    ]
