# Generated by Django 5.0.1 on 2024-01-09 22:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("o11y", "0014_remove_span_parent_span_id_span_parent_span"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="span",
            name="id",
        ),
        migrations.AlterField(
            model_name="span",
            name="span_id",
            field=models.CharField(max_length=16, primary_key=True, serialize=False),
        ),
    ]
