# Generated by Django 5.0.1 on 2024-01-09 23:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("o11y", "0015_remove_span_id_alter_span_span_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="span",
            name="parent_span",
        ),
        migrations.AddField(
            model_name="span",
            name="parent_span_id",
            field=models.CharField(default="x", max_length=16),
            preserve_default=False,
        ),
    ]
