apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask  # This should match the label in your Deployment
  ports:
    - protocol: TCP
      port: 8002  # Port to expose
      targetPort: 8002  # Port on the container
  type: NodePort  # Or any other type you prefer, like LoadBalancer
