# Generated by Django 4.2.2 on 2023-06-29 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProtoMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('unit', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='ProtoResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProtoResourceMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desktop.protoresource')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attributes_hash', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=256)),
                ('value', models.CharField(max_length=256)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desktop.resource')),
            ],
        ),
        migrations.CreateModel(
            name='ProtoScopeMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=256)),
                ('resource_metrics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desktop.protoresourcemetrics')),
            ],
        ),
        migrations.CreateModel(
            name='ProtoScalarMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(max_length=256)),
                ('aggregation_temporality', models.IntegerField()),
                ('is_monotonic', models.BooleanField()),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desktop.protometric')),
            ],
        ),
        migrations.CreateModel(
            name='ProtoResourceAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=256)),
                ('value', models.CharField(max_length=256)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desktop.protoresource')),
            ],
        ),
        migrations.CreateModel(
            name='ProtoNumberDataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('time', models.DateTimeField()),
                ('int_value', models.IntegerField(default=0)),
                ('scalar_metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desktop.protoscalarmetric')),
            ],
        ),
        migrations.AddField(
            model_name='protometric',
            name='scope_metrics',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desktop.protoscopemetrics'),
        ),
        migrations.CreateModel(
            name='MetricsProcessingRuns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('last_datapoint_processed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='desktop.protonumberdatapoint')),
            ],
        ),
    ]
