# Generated by Django 4.2.2 on 2023-06-30 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desktop', '0002_alter_resource_attributes_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScopeMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=256)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desktop.resource')),
            ],
        ),
    ]
