# Generated by Django 4.2.2 on 2023-06-30 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desktop', '0003_scopemetrics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('unit', models.CharField(max_length=32)),
                ('scope_metrics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desktop.scopemetrics')),
            ],
        ),
        migrations.CreateModel(
            name='ScalarMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(max_length=256)),
                ('aggregation_temporality', models.IntegerField()),
                ('is_monotonic', models.BooleanField()),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desktop.metric')),
            ],
        ),
        migrations.CreateModel(
            name='NumberDataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('time', models.DateTimeField()),
                ('int_value', models.IntegerField(default=0)),
                ('scalar_metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desktop.scalarmetric')),
            ],
        ),
    ]
