# Generated by Django 4.2.2 on 2023-07-10 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desktop', '0004_metric_scalarmetric_numberdatapoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protometric',
            name='scope_metrics',
        ),
        migrations.RemoveField(
            model_name='protonumberdatapoint',
            name='scalar_metric',
        ),
        migrations.RemoveField(
            model_name='protoresourceattribute',
            name='resource',
        ),
        migrations.RemoveField(
            model_name='protoresourcemetrics',
            name='resource',
        ),
        migrations.RemoveField(
            model_name='protoscalarmetric',
            name='metric',
        ),
        migrations.RemoveField(
            model_name='protoscopemetrics',
            name='resource_metrics',
        ),
        migrations.DeleteModel(
            name='MetricsProcessingRuns',
        ),
        migrations.DeleteModel(
            name='ProtoMetric',
        ),
        migrations.DeleteModel(
            name='ProtoNumberDataPoint',
        ),
        migrations.DeleteModel(
            name='ProtoResource',
        ),
        migrations.DeleteModel(
            name='ProtoResourceAttribute',
        ),
        migrations.DeleteModel(
            name='ProtoResourceMetrics',
        ),
        migrations.DeleteModel(
            name='ProtoScalarMetric',
        ),
        migrations.DeleteModel(
            name='ProtoScopeMetrics',
        ),
    ]
